# Generated by Django 6.0.2 on 2026-03-09 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_backfill_admin_level_and_seed_staff_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('max_ads_per_page', models.PositiveSmallIntegerField(default=1)),
                ('default_image_width', models.PositiveIntegerField(default=1200)),
                ('default_image_height', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('internal', 'King-Kush Promotion'), ('external', 'External Advertiser'), ('vendor', 'Vendor Sponsored Campaign')], db_index=True, default='external', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('target_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('creative_image', models.ImageField(blank=True, null=True, upload_to='advertising/creatives/')),
                ('category_context', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('is_sponsored', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=50)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricing_notes', models.CharField(blank=True, max_length=160)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('last_served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advertising_campaigns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advertising_campaigns', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_campaigns', to=settings.AUTH_USER_MODEL)),
                ('vendor_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_campaigns', to='users.vendorprofile')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertising.advertisingplacement')),
            ],
            options={
                'ordering': ('-priority', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='AdvertisingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], db_index=True, max_length=20)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('context_key', models.CharField(blank=True, max_length=120)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='advertising.advertisingcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdvertisingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('company_name', models.CharField(blank=True, max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('business_type', models.CharField(choices=[('vendor', 'Vendor'), ('brand', 'Brand'), ('agency', 'Agency'), ('platform', 'Platform'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('ad_objective', models.CharField(max_length=220)),
                ('campaign_duration', models.CharField(max_length=120)),
                ('budget_range', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('needs_info', 'Needs Information'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='advertising.advertisingplacement')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_advertising_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_requests', to='users.vendorprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='linked_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='advertising.advertisingrequest'),
        ),
        migrations.AddConstraint(
            model_name='advertisingcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('start_at__isnull', True), ('end_at__gte', models.F('start_at')), _connector='OR'), name='advertising_campaign_end_after_start'),
        ),
    ]
