"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.x.
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from decouple import Csv, config
from corsheaders.defaults import default_headers

try:
    import dj_database_url
except Exception:  # pragma: no cover - fallback for local envs without package installed yet
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    raw = config(name, default=None)
    if raw is None:
        return bool(default)
    normalized = str(raw).strip().lower()
    if normalized in {"1", "true", "t", "yes", "y", "on"}:
        return True
    if normalized in {"0", "false", "f", "no", "n", "off", ""}:
        return False
    return bool(default)

# Environment mode
ENVIRONMENT = config("ENVIRONMENT", default="development").strip().lower()
IS_PRODUCTION = ENVIRONMENT in {"production", "prod", "live"}
USE_S3_MEDIA = _env_bool("USE_S3_MEDIA", default=False)

# SECURITY WARNING: keep the secret key used in production secret.
_SECRET_KEY_FROM_ENV = config("SECRET_KEY", default="")
SECRET_KEY = _SECRET_KEY_FROM_ENV or get_random_secret_key()
SECRET_KEY_FROM_ENV = bool(_SECRET_KEY_FROM_ENV)
if IS_PRODUCTION and not SECRET_KEY_FROM_ENV:
    raise ImproperlyConfigured("SECRET_KEY must be set through environment variables in production.")

# SECURITY WARNING: don't run with debug turned on in production.
DEBUG = _env_bool("DEBUG", default=(not IS_PRODUCTION))
if IS_PRODUCTION and DEBUG:
    DEBUG = False

_DEFAULT_ALLOWED_HOSTS = (
    "kingkushstores.com,www.kingkushstores.com,api.kingkushstores.com,king-kush-stores.onrender.com"
    if IS_PRODUCTION
    else "localhost,127.0.0.1,0.0.0.0"
)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=_DEFAULT_ALLOWED_HOSTS, cast=Csv())
if IS_PRODUCTION:
    _required_hosts = {"king-kush-stores.onrender.com"}
    ALLOWED_HOSTS = list(dict.fromkeys([*ALLOWED_HOSTS, *_required_hosts]))

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'users',
    'products',
    'orders',
    'chatbot',
    'careers',
    'support',
    'content',
    'advertising',
    'promotions',
    'pickup',
    'receipts',
]
if USE_S3_MEDIA:
    INSTALLED_APPS.append("storages")

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database - use DATABASE_URL in production (e.g., Neon/Postgres), fallback to SQLite in local dev.
_DATABASE_URL = config("DATABASE_URL", default="").strip()
if IS_PRODUCTION:
    if not _DATABASE_URL:
        raise ImproperlyConfigured("DATABASE_URL must be set in production.")
    if not dj_database_url:
        raise ImproperlyConfigured("dj-database-url is required in production to parse DATABASE_URL.")
    DATABASES = {
        "default": dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=config("DB_CONN_MAX_AGE", default=600, cast=int),
        )
    }
elif _DATABASE_URL and dj_database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=config("DB_CONN_MAX_AGE", default=600, cast=int),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (Product Images, Vendor Logos, etc.)
# Default local storage is fine for dev, but not durable on ephemeral hosts.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if USE_S3_MEDIA:
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default="").strip()
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default="").strip()
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="").strip()
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="").strip() or None
    AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL", default="").strip() or None
    AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", default="").strip() or None
    AWS_S3_SIGNATURE_VERSION = config("AWS_S3_SIGNATURE_VERSION", default="s3v4").strip() or None
    AWS_MEDIA_LOCATION = config("AWS_MEDIA_LOCATION", default="media").strip("/") or "media"
    AWS_QUERYSTRING_AUTH = _env_bool("AWS_QUERYSTRING_AUTH", default=False)
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    _S3_MEDIA_URL = config("S3_MEDIA_URL", default="").strip()

    _missing_s3 = [
        name
        for name, value in {
            "AWS_ACCESS_KEY_ID": AWS_ACCESS_KEY_ID,
            "AWS_SECRET_ACCESS_KEY": AWS_SECRET_ACCESS_KEY,
            "AWS_STORAGE_BUCKET_NAME": AWS_STORAGE_BUCKET_NAME,
        }.items()
        if not value
    ]
    if _missing_s3:
        raise ImproperlyConfigured(
            f"USE_S3_MEDIA=True but required S3 vars are missing: {', '.join(_missing_s3)}"
        )

    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "signature_version": AWS_S3_SIGNATURE_VERSION,
            "default_acl": AWS_DEFAULT_ACL,
            "querystring_auth": AWS_QUERYSTRING_AUTH,
            "file_overwrite": AWS_S3_FILE_OVERWRITE,
            "location": AWS_MEDIA_LOCATION,
            "object_parameters": AWS_S3_OBJECT_PARAMETERS,
        },
    }

    if _S3_MEDIA_URL:
        MEDIA_URL = _S3_MEDIA_URL if _S3_MEDIA_URL.endswith("/") else f"{_S3_MEDIA_URL}/"
    elif AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN.rstrip('/')}/{AWS_MEDIA_LOCATION}/"
    elif AWS_S3_ENDPOINT_URL:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/{AWS_MEDIA_LOCATION}/"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- KING-KUSH STORES CUSTOM SETTINGS ---

# 1. Custom User Model configuration
AUTH_USER_MODEL = 'users.CustomUser'

# 2. CORS Policy
CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", default=False)
_DEFAULT_CORS_ALLOWED_ORIGINS = (
    (
        "https://kingkushstores.com,https://www.kingkushstores.com,"
        "https://king-kush-stores.vercel.app"
    )
    if IS_PRODUCTION
    else (
        "http://localhost:3000,http://127.0.0.1:3000,"
        "http://localhost:3001,http://127.0.0.1:3001,"
        "http://localhost:5173,http://127.0.0.1:5173,"
        "https://kingkushstores.com,https://www.kingkushstores.com"
    )
)
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default=_DEFAULT_CORS_ALLOWED_ORIGINS,
    cast=Csv(),
)
_CORS_ALLOWED_ORIGIN_REGEXES = config(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    default=(
        r"^http://localhost(:\d+)?$,"
        r"^http://127\.0\.0\.1(:\d+)?$"
        if not IS_PRODUCTION
        else (
            r"^https://.*\.vercel\.app$,"
            r"^https://.*\.onrender\.com$"
        )
    ),
    cast=Csv(),
)
CORS_ALLOWED_ORIGIN_REGEXES = [entry for entry in _CORS_ALLOWED_ORIGIN_REGEXES if str(entry).strip()]
if IS_PRODUCTION:
    _required_cors_origins = {
        "https://king-kush-stores.vercel.app",
    }
    _required_cors_regexes = {
        r"^https://.*\.vercel\.app$",
        r"^https://.*\.onrender\.com$",
    }
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys([*CORS_ALLOWED_ORIGINS, *_required_cors_origins]))
    CORS_ALLOWED_ORIGIN_REGEXES = list(dict.fromkeys([*CORS_ALLOWED_ORIGIN_REGEXES, *_required_cors_regexes]))

CORS_ALLOW_HEADERS = list(default_headers) + [
    "idempotency-key",
]
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default=(
        (
            "https://kingkushstores.com,https://www.kingkushstores.com,"
            "https://king-kush-stores.vercel.app,https://*.vercel.app"
        )
        if IS_PRODUCTION
        else (
            "http://localhost:3000,http://127.0.0.1:3000,"
            "http://localhost:3001,http://127.0.0.1:3001,"
            "http://localhost:5173,http://127.0.0.1:5173,"
            "https://kingkushstores.com,https://www.kingkushstores.com"
        )
    ),
    cast=Csv(),
)
if IS_PRODUCTION:
    _required_csrf_origins = {
        "https://king-kush-stores.vercel.app",
        "https://*.vercel.app",
        "https://king-kush-stores.onrender.com",
    }
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([*CSRF_TRUSTED_ORIGINS, *_required_csrf_origins]))
if IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = False

# 3. Django REST Framework global settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Marketplace finance defaults
MARKETPLACE_COMMISSION_RATE = config("MARKETPLACE_COMMISSION_RATE", default=0.10, cast=float)
MARKETPLACE_MPESA_ACCOUNT_REFERENCE = config("MARKETPLACE_MPESA_ACCOUNT_REFERENCE", default="0701137747")
MARKETPLACE_PAYOUT_MODE = config("MARKETPLACE_PAYOUT_MODE", default="automatic")  # automatic | manual
MARKETPLACE_EARNINGS_RELEASE_POLICY = config("MARKETPLACE_EARNINGS_RELEASE_POLICY", default="on_payment")  # on_payment | on_delivery
MARKETPLACE_STOCK_RESERVATION_MINUTES = config("MARKETPLACE_STOCK_RESERVATION_MINUTES", default=30, cast=int)  # hold stock for unpaid checkout orders

# M-Pesa integration configuration
MPESA_ENVIRONMENT = config("MPESA_ENVIRONMENT", default=config("MPESA_ENV", default="sandbox")).strip().lower()
MPESA_ENABLE_LIVE = _env_bool("MPESA_ENABLE_LIVE", default=(MPESA_ENVIRONMENT in {"production", "live"}))
MPESA_ENV = MPESA_ENVIRONMENT  # sandbox | production/live
MPESA_CONSUMER_KEY = config("MPESA_CONSUMER_KEY", default="")
MPESA_CONSUMER_SECRET = config("MPESA_CONSUMER_SECRET", default="")
MPESA_SHORTCODE = config("MPESA_SHORTCODE", default="")
MPESA_PASSKEY = config("MPESA_PASSKEY", default="")
MPESA_STK_TRANSACTION_TYPE = config("MPESA_STK_TRANSACTION_TYPE", default="CustomerPayBillOnline")
MPESA_STK_CALLBACK_URL = config("MPESA_STK_CALLBACK_URL", default="")

# B2C automated payout configuration
MPESA_B2C_SHORTCODE = config("MPESA_B2C_SHORTCODE", default="")
MPESA_B2C_INITIATOR_NAME = config("MPESA_B2C_INITIATOR_NAME", default="")
MPESA_B2C_SECURITY_CREDENTIAL = config("MPESA_B2C_SECURITY_CREDENTIAL", default="")
MPESA_B2C_RESULT_URL = config("MPESA_B2C_RESULT_URL", default="")
MPESA_B2C_TIMEOUT_URL = config("MPESA_B2C_TIMEOUT_URL", default="")
MPESA_B2C_COMMAND_ID = config("MPESA_B2C_COMMAND_ID", default="BusinessPayment")

# Production security hardening
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=IS_PRODUCTION)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool("SECURE_CONTENT_TYPE_NOSNIFF", default=IS_PRODUCTION)
SECURE_REFERRER_POLICY = config("SECURE_REFERRER_POLICY", default="strict-origin-when-cross-origin")
X_FRAME_OPTIONS = config("X_FRAME_OPTIONS", default="DENY")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=(31536000 if IS_PRODUCTION else 0), cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=IS_PRODUCTION)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", default=IS_PRODUCTION)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        }
    },
}
