"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.x.
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    raw = config(name, default=None)
    if raw is None:
        return bool(default)
    normalized = str(raw).strip().lower()
    if normalized in {"1", "true", "t", "yes", "y", "on"}:
        return True
    if normalized in {"0", "false", "f", "no", "n", "off", ""}:
        return False
    return bool(default)

# Environment mode
ENVIRONMENT = config("ENVIRONMENT", default="development").strip().lower()
IS_PRODUCTION = ENVIRONMENT in {"production", "prod", "live"}

# SECURITY WARNING: keep the secret key used in production secret.
_SECRET_KEY_FROM_ENV = config("SECRET_KEY", default="")
SECRET_KEY = _SECRET_KEY_FROM_ENV or get_random_secret_key()
SECRET_KEY_FROM_ENV = bool(_SECRET_KEY_FROM_ENV)
if IS_PRODUCTION and not SECRET_KEY_FROM_ENV:
    raise ImproperlyConfigured("SECRET_KEY must be set through environment variables in production.")

# SECURITY WARNING: don't run with debug turned on in production.
DEBUG = _env_bool("DEBUG", default=(not IS_PRODUCTION))
if IS_PRODUCTION and DEBUG:
    DEBUG = False

_DEFAULT_ALLOWED_HOSTS = (
    "kingkushstores.com,www.kingkushstores.com,api.kingkushstores.com"
    if IS_PRODUCTION
    else "localhost,127.0.0.1,0.0.0.0"
)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=_DEFAULT_ALLOWED_HOSTS, cast=Csv())

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'users',
    'products',
    'orders',
    'chatbot',
    'careers',
    'support',
    'advertising',
    'promotions',
    'pickup',
    'receipts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database - Defaulting to SQLite for initial setup, we will switch to PostgreSQL soon
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (Product Images, Vendor Logos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- KING-KUSH STORES CUSTOM SETTINGS ---

# 1. Custom User Model configuration
AUTH_USER_MODEL = 'users.CustomUser'

# 2. CORS Policy
CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", default=False)
_DEFAULT_CORS_ALLOWED_ORIGINS = (
    "https://kingkushstores.com,https://www.kingkushstores.com"
    if IS_PRODUCTION
    else (
        "http://localhost:3000,http://127.0.0.1:3000,"
        "http://localhost:3001,http://127.0.0.1:3001,"
        "http://localhost:5173,http://127.0.0.1:5173,"
        "https://kingkushstores.com,https://www.kingkushstores.com"
    )
)
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default=_DEFAULT_CORS_ALLOWED_ORIGINS,
    cast=Csv(),
)
_CORS_ALLOWED_ORIGIN_REGEXES = config(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    default=(
        r"^http://localhost(:\d+)?$,"
        r"^http://127\.0\.0\.1(:\d+)?$"
        if not IS_PRODUCTION
        else ""
    ),
    cast=Csv(),
)
CORS_ALLOWED_ORIGIN_REGEXES = [entry for entry in _CORS_ALLOWED_ORIGIN_REGEXES if str(entry).strip()]
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default=(
        "https://kingkushstores.com,https://www.kingkushstores.com"
        if IS_PRODUCTION
        else (
            "http://localhost:3000,http://127.0.0.1:3000,"
            "http://localhost:3001,http://127.0.0.1:3001,"
            "http://localhost:5173,http://127.0.0.1:5173,"
            "https://kingkushstores.com,https://www.kingkushstores.com"
        )
    ),
    cast=Csv(),
)
if IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = False

# 3. Django REST Framework global settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Marketplace finance defaults
MARKETPLACE_COMMISSION_RATE = config("MARKETPLACE_COMMISSION_RATE", default=0.10, cast=float)
MARKETPLACE_MPESA_ACCOUNT_REFERENCE = config("MARKETPLACE_MPESA_ACCOUNT_REFERENCE", default="0701137747")
MARKETPLACE_PAYOUT_MODE = config("MARKETPLACE_PAYOUT_MODE", default="automatic")  # automatic | manual
MARKETPLACE_EARNINGS_RELEASE_POLICY = config("MARKETPLACE_EARNINGS_RELEASE_POLICY", default="on_payment")  # on_payment | on_delivery
MARKETPLACE_STOCK_RESERVATION_MINUTES = config("MARKETPLACE_STOCK_RESERVATION_MINUTES", default=30, cast=int)  # hold stock for unpaid checkout orders

# M-Pesa integration configuration
MPESA_ENVIRONMENT = config("MPESA_ENVIRONMENT", default=config("MPESA_ENV", default="sandbox")).strip().lower()
MPESA_ENABLE_LIVE = _env_bool("MPESA_ENABLE_LIVE", default=(MPESA_ENVIRONMENT in {"production", "live"}))
MPESA_ENV = MPESA_ENVIRONMENT  # sandbox | production/live
MPESA_CONSUMER_KEY = config("MPESA_CONSUMER_KEY", default="")
MPESA_CONSUMER_SECRET = config("MPESA_CONSUMER_SECRET", default="")
MPESA_SHORTCODE = config("MPESA_SHORTCODE", default="")
MPESA_PASSKEY = config("MPESA_PASSKEY", default="")
MPESA_STK_TRANSACTION_TYPE = config("MPESA_STK_TRANSACTION_TYPE", default="CustomerPayBillOnline")
MPESA_STK_CALLBACK_URL = config("MPESA_STK_CALLBACK_URL", default="")

# B2C automated payout configuration
MPESA_B2C_SHORTCODE = config("MPESA_B2C_SHORTCODE", default="")
MPESA_B2C_INITIATOR_NAME = config("MPESA_B2C_INITIATOR_NAME", default="")
MPESA_B2C_SECURITY_CREDENTIAL = config("MPESA_B2C_SECURITY_CREDENTIAL", default="")
MPESA_B2C_RESULT_URL = config("MPESA_B2C_RESULT_URL", default="")
MPESA_B2C_TIMEOUT_URL = config("MPESA_B2C_TIMEOUT_URL", default="")
MPESA_B2C_COMMAND_ID = config("MPESA_B2C_COMMAND_ID", default="BusinessPayment")

# Production security hardening
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=IS_PRODUCTION)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool("SECURE_CONTENT_TYPE_NOSNIFF", default=IS_PRODUCTION)
SECURE_REFERRER_POLICY = config("SECURE_REFERRER_POLICY", default="strict-origin-when-cross-origin")
X_FRAME_OPTIONS = config("X_FRAME_OPTIONS", default="DENY")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=(31536000 if IS_PRODUCTION else 0), cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=IS_PRODUCTION)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", default=IS_PRODUCTION)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        }
    },
}
