# Generated by Django 6.0.2 on 2026-03-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_verified_at_marketplacepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
