# Generated by Django 6.0.2 on 2026-03-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_original_price'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='promotion_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='promotions.promotionoffer'),
        ),
    ]
