# Generated by Django 6.0.2 on 2026-03-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_promotion_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup Station')], db_index=True, default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
