# Generated by Django 6.0.2 on 2026-03-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_pickup_station'),
        ('products', '0003_product_auto_price_calculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sale_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productsaleoption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_option_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_option_quantity_unit',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_option_quantity_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_option_stock_units_consumed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
