# Generated by Codex on 2026-03-08
from django.db import migrations


def seed_defaults(apps, schema_editor):
    JobOpening = apps.get_model("careers", "JobOpening")
    JobApplicationField = apps.get_model("careers", "JobApplicationField")

    default_openings = [
        {
            "title": "Senior Frontend Developer",
            "department": "Engineering",
            "location": "Nairobi, Kenya",
            "employment_type": "full_time",
            "summary": "Build high-performance web interfaces that power the King-Kush customer experience.",
            "responsibilities": "Own key frontend features, collaborate with backend teams, and improve UX quality.",
            "requirements": "React/Next.js experience, strong TypeScript knowledge, and shipping production-grade UI.",
            "is_active": True,
        },
        {
            "title": "Product Manager - Fintech",
            "department": "Product",
            "location": "Nairobi, Kenya",
            "employment_type": "full_time",
            "summary": "Lead payments and checkout product improvements across the King-Kush platform.",
            "responsibilities": "Define roadmap, align stakeholders, and deliver measurable customer outcomes.",
            "requirements": "Proven product management track record in e-commerce or fintech.",
            "is_active": True,
        },
        {
            "title": "Digital Marketing Specialist",
            "department": "Marketing",
            "location": "Remote",
            "employment_type": "contract",
            "summary": "Scale customer acquisition through SEO, paid campaigns, and retention programs.",
            "responsibilities": "Run campaigns, optimize conversion funnels, and report weekly performance metrics.",
            "requirements": "Hands-on growth marketing execution and analytics proficiency.",
            "is_active": True,
        },
    ]

    for opening in default_openings:
        JobOpening.objects.get_or_create(
            title=opening["title"],
            defaults=opening,
        )

    default_fields = [
        ("full_name", "Full Name", "text", True, "Enter your full legal name", "", [], 1),
        ("email", "Email Address", "email", True, "you@example.com", "", [], 2),
        ("phone_number", "Phone Number", "phone", True, "e.g. +254712345678", "", [], 3),
        ("country_location", "Country / Location", "text", True, "e.g. Kenya, Nairobi", "", [], 4),
        ("years_of_experience", "Years of Experience", "number", True, "e.g. 5", "", [], 5),
        (
            "education_level",
            "Education Level",
            "select",
            True,
            "",
            "",
            ["High School", "Diploma", "Bachelor's Degree", "Master's Degree", "Doctorate", "Other"],
            6,
        ),
        (
            "professional_skills",
            "Professional Skills",
            "textarea",
            True,
            "List your core skills and tools",
            "",
            [],
            7,
        ),
        ("linkedin_portfolio", "LinkedIn / Portfolio", "url", False, "https://", "Optional", [], 8),
        ("cover_letter", "Cover Letter", "textarea", True, "Write a brief introduction", "", [], 9),
    ]

    for key, label, field_type, required, placeholder, help_text, options, sort_order in default_fields:
        JobApplicationField.objects.get_or_create(
            key=key,
            defaults={
                "label": label,
                "field_type": field_type,
                "is_required": required,
                "placeholder": placeholder,
                "help_text": help_text,
                "select_options": options,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


def reverse_seed_defaults(apps, schema_editor):
    JobApplicationField = apps.get_model("careers", "JobApplicationField")
    JobOpening = apps.get_model("careers", "JobOpening")

    JobApplicationField.objects.filter(
        key__in=[
            "full_name",
            "email",
            "phone_number",
            "country_location",
            "years_of_experience",
            "education_level",
            "professional_skills",
            "linkedin_portfolio",
            "cover_letter",
        ]
    ).delete()

    JobOpening.objects.filter(
        title__in=[
            "Senior Frontend Developer",
            "Product Manager - Fintech",
            "Digital Marketing Specialist",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_defaults, reverse_seed_defaults),
    ]
