# Generated by Django 6.0.2 on 2026-03-10 09:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_price_calculation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_quantity_value',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit_label',
            field=models.CharField(default='item', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('single_item', 'Single Item'), ('piece_based', 'Piece Based'), ('pack_based', 'Pack Based'), ('weight_based', 'Weight Based'), ('volume_based', 'Volume Based'), ('set_bundle', 'Set / Bundle'), ('custom', 'Custom')], db_index=True, default='single_item', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_unit_label',
            field=models.CharField(default='unit', max_length=40),
        ),
        migrations.CreateModel(
            name='ProductSaleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('quantity_value', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('quantity_unit', models.CharField(blank=True, default='', max_length=40)),
                ('base_quantity_equivalent', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('stock_units_consumed', models.PositiveIntegerField(default=1)),
                ('use_manual_price', models.BooleanField(default=False)),
                ('manual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_options', to='products.product')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
