# Generated by Django 6.0.2 on 2026-03-09 06:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_specifications'),
        ('users', '0009_backfill_admin_level_and_seed_staff_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('black_friday', 'Black Friday')], db_index=True, default='black_friday', max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hero_title', models.CharField(blank=True, max_length=220)),
                ('hero_subtitle', models.CharField(blank=True, max_length=280)),
                ('hero_cta_label', models.CharField(default='Shop Deals', max_length=60)),
                ('hero_cta_url', models.CharField(blank=True, max_length=255)),
                ('countdown_label', models.CharField(default='Sale ends in', max_length=90)),
                ('announcement_text', models.CharField(blank=True, max_length=220)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/banners/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='draft', max_length=20)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sections_config', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_campaigns_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PromotionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor')], default='admin', max_length=20)),
                ('review_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=20)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('promotional_stock_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('promotional_stock_sold', models.PositiveIntegerField(default=0)),
                ('section_key', models.CharField(db_index=True, default='best_deals', max_length=80)),
                ('badge_text', models.CharField(default='Black Friday Deal', max_length=90)),
                ('urgency_text', models.CharField(blank=True, max_length=90)),
                ('is_flash_deal', models.BooleanField(db_index=True, default=False)),
                ('flash_start_at', models.DateTimeField(blank=True, null=True)),
                ('flash_end_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_offers_approved', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='promotions.promotioncampaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_offers', to='products.product')),
                ('submitted_by_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_offers_submitted', to='users.vendorprofile')),
            ],
            options={
                'ordering': ('-priority', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], db_index=True, max_length=20)),
                ('page_path', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_events', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='promotions.promotionoffer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='promotioncampaign',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='promotion_campaign_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='promotionoffer',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gte', 0)), name='promotion_offer_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='promotionoffer',
            constraint=models.CheckConstraint(condition=models.Q(('promotional_stock_limit__isnull', True), ('promotional_stock_limit__gt', 0), _connector='OR'), name='promotion_offer_stock_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='promotionoffer',
            constraint=models.CheckConstraint(condition=models.Q(('flash_end_at__isnull', True), ('flash_start_at__isnull', True), ('flash_end_at__gte', models.F('flash_start_at')), _connector='OR'), name='promotion_offer_flash_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='promotionoffer',
            constraint=models.CheckConstraint(condition=models.Q(('promotional_stock_limit__isnull', True), ('promotional_stock_sold__lte', models.F('promotional_stock_limit')), _connector='OR'), name='promotion_offer_sold_not_above_limit'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionoffer',
            unique_together={('campaign', 'product')},
        ),
    ]
