from __future__ import annotations

import textwrap


def _escape_pdf_text(value: str) -> str:
    cleaned = str(value or "").replace("\r", " ").replace("\n", " ")
    cleaned = cleaned.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
    return cleaned


def _flatten_lines(lines: list[str], width: int = 36) -> list[str]:
    flattened: list[str] = []
    for line in lines:
        wrapped = textwrap.wrap(str(line or ""), width=width) or [""]
        flattened.extend(wrapped)
    return flattened


def build_simple_receipt_pdf(lines: list[str]) -> bytes:
    rendered_lines = _flatten_lines(lines)
    # Slim receipt-strip layout (narrow and long, POS style).
    page_width = 230
    top_margin = 24
    bottom_margin = 20
    line_height = 12
    start_x = 16
    start_y = max(20, top_margin + (len(rendered_lines) * line_height))
    page_height = start_y + bottom_margin

    text_cmds: list[str] = [
        "BT",
        "/F1 9 Tf",
        f"{start_x} {start_y} Td",
    ]
    for idx, line in enumerate(rendered_lines):
        if idx > 0:
            text_cmds.append(f"0 -{line_height} Td")
        text_cmds.append(f"({_escape_pdf_text(line)}) Tj")
    text_cmds.append("ET")
    content_stream = "\n".join(text_cmds).encode("latin-1", errors="replace")

    objects: list[bytes] = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Count 1 /Kids [3 0 R] >>")
    objects.append(
        f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {page_width} {page_height}] "
        f"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>".encode("ascii")
    )
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    objects.append(
        b"<< /Length %d >>\nstream\n" % len(content_stream)
        + content_stream
        + b"\nendstream"
    )

    pdf = bytearray()
    pdf.extend(b"%PDF-1.4\n")
    pdf.extend(b"%Generated by King-Kush Receipts\n")

    offsets = [0]
    for idx, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{idx} 0 obj\n".encode("ascii"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")

    xref_pos = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("ascii"))

    pdf.extend(
        (
            "trailer\n"
            f"<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            "startxref\n"
            f"{xref_pos}\n"
            "%%EOF\n"
        ).encode("ascii")
    )
    return bytes(pdf)
