# Generated by Django 6.0.2 on 2026-03-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='receipt',
            new_name='receipts_re_categor_04892c_idx',
            old_name='receipts_re_categor_c5fc1f_idx',
        ),
        migrations.RenameIndex(
            model_name='receipt',
            new_name='receipts_re_owner_t_8d2ca0_idx',
            old_name='receipts_re_owner_t_6f8ced_idx',
        ),
    ]
