# Generated by Django 6.0.2 on 2026-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accountactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivity',
            name='activity_type',
            field=models.CharField(choices=[('profile_update', 'Profile Update'), ('order_create', 'Order Created'), ('order_cancel', 'Order Cancelled'), ('address_create', 'Address Added'), ('address_update', 'Address Updated'), ('address_delete', 'Address Deleted'), ('payment_create', 'Payment Method Added'), ('payment_update', 'Payment Method Updated'), ('payment_delete', 'Payment Method Deleted'), ('job_application', 'Job Application Submitted')], max_length=40),
        ),
    ]
