# Generated by Codex on 2026-03-08
from django.db import migrations


def set_vendor_status_from_is_approved(apps, schema_editor):
    VendorProfile = apps.get_model("users", "VendorProfile")
    VendorProfile.objects.filter(is_approved=True).update(approval_status="approved")
    VendorProfile.objects.filter(is_approved=False, approval_status="approved").update(approval_status="pending_review")


def reverse_vendor_status_backfill(apps, schema_editor):
    VendorProfile = apps.get_model("users", "VendorProfile")
    VendorProfile.objects.filter(approval_status="approved").update(is_approved=True)
    VendorProfile.objects.exclude(approval_status="approved").update(is_approved=False)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_vendorprofile_approval_status_and_more"),
    ]

    operations = [
        migrations.RunPython(set_vendor_status_from_is_approved, reverse_vendor_status_backfill),
    ]
