# Generated by Django 6.0.2 on 2026-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_backfill_vendor_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_postal_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_branding/banners/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_branding/logos/'),
        ),
    ]
