# Generated by Django 6.0.2 on 2026-03-09 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_fulfillment_method_order_picked_up_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('operating_hours', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('supports_pickup', models.BooleanField(default=True)),
                ('supports_returns', models.BooleanField(default=True)),
                ('temporary_notice', models.TextField(blank=True)),
                ('notice_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_stations_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_stations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('city', 'name'),
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='PickupOrderOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ready_for_pickup', 'Ready For Pickup'), ('collected', 'Collected'), ('return_dropoff', 'Return Drop-off'), ('notice_update', 'Station Notice Update')], db_index=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_operations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_operations', to='orders.order')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='pickup.pickupstation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PickupStationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('can_manage_local_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pickup.pickupstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_station_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('station__city', 'station__name', 'user__email'),
                'unique_together': {('station', 'user')},
            },
        ),
    ]
